on:
  push:
    branches:
      - main
jobs:
  build-wheels-and-publish:
    name: Build Wheels and Publish
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: bash ./setup-pythons.bash
      - run: bash ./build.bash
